swagger: '2.0'
info:
  title: AI Photo Search
  description: 'AI Photo Search application, built during the Cloud and Big Data course at Columbia University.'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
consumes:
  - image/png
  - image/jpg
  - image/jpeg
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /photos:
    put:
      summary: photo upload method
      description: |
        This API takes in the multi-part body sent to it (ex. a photo) and uploads it to an S3 bucket.
      operationId: uploadPhoto
      consumes:
        - image/png
        - image/jpg
        - image/jpeg
      produces:
        - application/json
      parameters:
        - name: x-amz-meta-customLabels
          in: header
          required: false
          type: string
          description: Custom labels to be added to the photo metadata (comma-separated)
        - name: objectKey
          in: query
          required: true
          type: string
          description: The S3 object key (filename) for the uploaded photo
      security:
        - api_key: [94MfH0ZkQHMFfbCFTR5YaO8QdjMRHFe1Gy1UQQD9]
      responses:
        '200':
          description: S3 PUT operation response
          schema:
            type: object
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Methods:
              type: string
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
          headers:
            Access-Control-Allow-Origin:
              type: string
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
          headers:
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        type: aws
        uri: 'arn:aws:apigateway:us-east-1:s3:path/amzn-s3-b2-photos/{objectKey}'
        httpMethod: PUT
        credentials: 'arn:aws:iam::244086559221:role/api-gateway-s3-role'
        requestParameters:
          integration.request.path.objectKey: 'method.request.querystring.objectKey'
          integration.request.header.x-amz-meta-customLabels: 'method.request.header.x-amz-meta-customLabels'
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_BINARY
        responses:
          '200':
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-api-key,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
          '403':
            statusCode: '403'
            selectionPattern: '4\\d{2}'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-api-key,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
            responseTemplates:
              application/json: |
                {
                  "code": 403,
                  "message": "Forbidden"
                }
          '500':
            statusCode: '500'
            selectionPattern: '5\\d{2}'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-api-key,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
            responseTemplates:
              application/json: |
                {
                  "code": 500,
                  "message": "Internal Server Error"
                }
  /search:
    get:
      summary: photo search method
      description: |
        This API takes in a search query as a query parameter and returns zero or more photos that match the search query.
      operationId: searchPhotos
      produces:
        - application/json
      parameters:
        - in: query
          name: q
          required: true
          type: string
          description: the string to be searched
      security:
        - api_key: [94MfH0ZkQHMFfbCFTR5YaO8QdjMRHFe1Gy1UQQD9]
      responses:
        '200':
          description: search results
          schema:
            $ref: '#/definitions/SearchResponse'
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Methods:
              type: string
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
          headers:
            Access-Control-Allow-Origin:
              type: string
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
          headers:
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:244086559221:function:LF2/invocations'
        httpMethod: POST
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-api-key,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
x-amazon-apigateway-request-validators:
  validate-request-params:
    validateRequestParameters: true
    validateRequestBody: false
  validate-all:
    validateRequestParameters: true
    validateRequestBody: true
definitions:
  SearchResponse:
    type: object
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/Photo'
  Photo:
    type: object
    properties:
      url:
        type: string
      labels:
        type: array
        items:
          type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

